// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: NetProto.proto

#pragma warning disable 1591, 0612, 3021

namespace Net
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PacketSession : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PacketSession()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int SessionId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PacketType PType { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int CmdId { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum PacketType
        {
            Post = 0,
            Notify = 1,
            Request = 2,
            Response = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CommonRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public CommonRsp()
        {
            ErrorStr = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorStr { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum CmdId
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CMD_ID")]
            CmdId = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartBeat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public HeartBeat()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoContract()]
        public enum CmdId
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CMD_ID")]
            CmdId = 2,
        }

    }

}

#pragma warning restore 1591, 0612, 3021
